### ISSUE TITLE
Вернуть выделение текста

### ISSUE THREAD

**Issue by 1999** [1999/vkoffline#55]
> Можно ли вернуть, чтобы текст в диалогах выделялся? К примеру, отправил одному собеседнику сообщение, захотелось поделиться этим же или частью, выделить нельзя и приходится набирать заново. Тоже и к ссылкам относится, только тут возможность копирования через правую кнопку мыши.

**Comment by wirusoal** [comment]
Можно, в помощь -webkit-user-select: text; ставим в блок, где хотим сделать доступным выделение.

**Comment by 1999** [comment]
@wirusoal угу, может сделаете пулреквест?

**Comment by wirusoal** [comment]
@1999  на github только недавно сижу, много чего не понятно, но вроде получилось

**Comment by 1999** [comment]
@wirusoal поздравляю в первом успешном контрибьюте в опенсорс :)
Новая версия приложения на рассмотрении в Chrome Web Store. Через полчаса начнет раскатываться.
