### ISSUE TITLE
Экспорт данных из IndexedDB в JSON

### ISSUE THREAD

**Issue by 57ar7up** [1999/vkoffline#59]
Неужели это так сложно?

**Comment by 1999** [comment]
В целом конечно можно, если не учитывать всякие ключи, но в чем смысл?

**Comment by 57ar7up** [comment]
По сути нет готовых решений экспорта переписки и контактов из ВК в этот распространённый формат. Для массового пользователя, это может и не нужно, но например для специалистов по анализу данных это было бы крайне полезно

**Comment by 1999** [comment]
*Специалисты по анализу данных* могли бы сами используя API ВКонтакте выгрузить все сообщения, не используя промежуточное хранилища типа того, что используется в VK Offline. Разве не так?
